name: Build and Optimize Blazor WASM

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  packages: read  # Give permissions to read from GitHub Packages

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PROJECT_DIR: FallenClient

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install wasm-tools workload
        run: dotnet workload install wasm-tools
        working-directory: ${{ env.PROJECT_DIR }}

      - name: Add GitHub Packages to NuGet sources
        run: |
          dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ${{ env.PROJECT_DIR }}

      - name: Build and publish Blazor WASM app
        run: dotnet publish -c Release -o release
        working-directory: ${{ env.PROJECT_DIR }}

      - name: Zip build contents
        run: |
          cd ${{ env.PROJECT_DIR }}/release/wwwroot
          zip -r ../blazor-wasm-app.zip ./*

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: blazor-wasm-app
          path: ${{ env.PROJECT_DIR }}/release/blazor-wasm-app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    env:
      REGION: us-west-2

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: blazor-wasm-app

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::375376062993:role/Github-Deployment
          aws-region: ${{ env.REGION }}

      - name: Deploy to AWS Amplify
        run: |
            aws s3 cp blazor-wasm-app.zip s3://fallen-client/blazor-wasm-app.zip --acl bucket-owner-full-control
            aws amplify start-deployment --app-id d4v4kn7dlfnjo --branch-name main --source-url s3://fallen-client/blazor-wasm-app.zip
